import os
import sqlite3

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "odin_ai", "db", "odin_archive.db")

class HuginnThoughtEngine:
    """
    Acts as Odin's perspective—fetching, reading, and displaying 
    the intelligence profiles generated by the background agents.
    """
    def __init__(self):
        if not os.path.exists(DB_PATH):
            print("[!] Error: The memory database (odin_archive.db) does not exist yet.")
            self.connected = False
        else:
            self.connected = True

    def recall_all_intelligence(self):
        if not self.connected:
            return

        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        # Fetch everything that has been processed by the agents
        cursor.execute("""
            SELECT id, filename, file_type, file_hash, profile_summary 
            FROM file_archive 
            WHERE processing_status = 'Analyzed'
            ORDER BY id DESC
        """)
        records = cursor.fetchall()

        print("\n" + "="*55)
        print(f"[!] HUGINN INTELLIGENCE RETRIEVAL ──► {len(records)} ASSETS RECALLED")
        print("="*55)

        if not records:
            print("[-] Huginn scanned the archive but found no analyzed thoughts yet.")
            print("[*] Ensure the daemon is running and processing Muninn's inputs.")
            conn.close()
            return

        for record_id, filename, file_type, file_hash, summary in records:
            print(f"\n[Asset ID: {record_id}] {filename} ({file_type.upper()})")
            print(f" ↳ SHA-256: {file_hash[:16]}...")
            print(f" ↳ AI Thought Profile:")
            # Indent the AI summary so it looks clean in Termux
            indented_summary = "\n".join([f"    {line}" for line in summary.split("\n")])
            print(indented_summary)
            print("-" * 40)

        conn.close()

if __name__ == "__main__":
    huginn = HuginnThoughtEngine()
    huginn.recall_all_intelligence()
